package com.example.aplicacionegipto.ui.screens

import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.VolumeUp
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.semantics.*
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.aplicacionegipto.data.MuseumRepository
import com.example.aplicacionegipto.model.AgeGroup
import com.example.aplicacionegipto.ui.components.MuseumAsyncImage
import com.example.aplicacionegipto.ui.theme.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ArticleDetailScreen(sectionId: String, articleId: String, onBack: () -> Unit, onImageClick: (Int) -> Unit) {
    var selectedAge by remember { mutableStateOf(AgeGroup.ADULT) }
    val idx = articleId.removePrefix("article_").toIntOrNull() ?: 0
    val urls = MuseumRepository.getImageUrls(sectionId)
    val url = urls.getOrNull(idx) ?: ""
    val title = getTitle(sectionId, idx)
    val content = getContent(sectionId, idx, selectedAge)

    Scaffold(topBar = { TopAppBar(title = { Text(title, style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold), maxLines = 1) },
        navigationIcon = { IconButton(onClick = onBack) { Icon(Icons.AutoMirrored.Filled.ArrowBack, "Regresar") } },
        actions = { IconButton(onClick = {}, modifier = Modifier.semantics { contentDescription = "Reproducir audio descriptivo del articulo" }) { Icon(Icons.Default.VolumeUp, null, tint = MaterialTheme.colorScheme.primary) } },
        colors = TopAppBarDefaults.topAppBarColors(containerColor = MaterialTheme.colorScheme.background)) }) { pv ->
        Column(Modifier.fillMaxSize().padding(pv).verticalScroll(rememberScrollState())) {
            Row(Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp).semantics { contentDescription = "Selector de nivel. Mostrando contenido para ${selectedAge.label}." }, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                AgeGroup.entries.forEach { age -> FilterChip(selected = age == selectedAge, onClick = { selectedAge = age }, label = { Text(when(age) { AgeGroup.CHILD -> "Ninos"; AgeGroup.TEEN -> "Adolescentes"; AgeGroup.ADULT -> "Adultos" }) }, colors = FilterChipDefaults.filterChipColors(selectedContainerColor = MaterialTheme.colorScheme.primary, selectedLabelColor = MaterialTheme.colorScheme.onPrimary)) }
            }
            Card(Modifier.fillMaxWidth().height(200.dp).padding(horizontal = 16.dp).clickable { onImageClick(0) }.semantics { contentDescription = "Imagen del articulo. Toca para ampliar con zoom." }, shape = RoundedCornerShape(12.dp)) {
                if (url.isNotEmpty()) MuseumAsyncImage(url, "Imagen de $title", Modifier.fillMaxSize())
                else Box(Modifier.fillMaxSize().background(Brush.verticalGradient(listOf(LapisLazuli.copy(alpha = 0.4f), GoldDark.copy(alpha = 0.3f)))), contentAlignment = Alignment.Center) { Text("Toca para ampliar", style = MaterialTheme.typography.bodySmall, color = Color.White) }
            }
            Spacer(Modifier.height(16.dp))
            Column(Modifier.padding(horizontal = 16.dp).semantics { contentDescription = "Articulo: $title. Contenido para ${selectedAge.label}." }) {
                Text(title, style = MaterialTheme.typography.headlineMedium.copy(fontWeight = FontWeight.Bold), color = MaterialTheme.colorScheme.primary)
                Spacer(Modifier.height(4.dp)); Text("Contenido para ${selectedAge.label}", style = MaterialTheme.typography.labelMedium, color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f))
                Box(Modifier.padding(vertical = 12.dp).fillMaxWidth().height(2.dp).background(Brush.horizontalGradient(listOf(MaterialTheme.colorScheme.primary, MaterialTheme.colorScheme.primary.copy(alpha = 0f)))))
                Text(content, style = MaterialTheme.typography.bodyLarge, color = MaterialTheme.colorScheme.onSurface, lineHeight = 26.sp)
                Spacer(Modifier.height(16.dp))
                Text("Desliza para ver el articulo anterior o siguiente", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.4f), textAlign = TextAlign.Center, modifier = Modifier.fillMaxWidth())
                Spacer(Modifier.height(24.dp))
            }
        }
    }
}

private fun getTitle(sid: String, idx: Int) = when(sid) {
    "vida_cotidiana" -> listOf("Alimentacion y cocina","Vestimenta y joyeria","La familia egipcia","Juegos y entretenimiento","Medicina y salud").getOrElse(idx) { "Articulo" }
    "arquitectura"   -> listOf("Las Grandes Piramides de Giza","Templos de Karnak y Luxor","La Gran Esfinge","Tumbas del Valle de los Reyes","Obeliscos y columnas").getOrElse(idx) { "Articulo" }
    "arte"           -> listOf("Jeroglificos: escritura sagrada","Pintura mural y frescos","Escultura y estatuaria","Mascara de Tutankamon","Arte funerario y sarcofagos").getOrElse(idx) { "Articulo" }
    else -> "Articulo del Museo"
}

private fun getContent(sid: String, idx: Int, age: AgeGroup): String = when(sid) {

    // ===================== VIDA COTIDIANA =====================
    "vida_cotidiana" -> when(idx) {

        // Art.1 — Alimentacion (imagen: Panaderia Meketre)
        0 -> when(age) {
            AgeGroup.CHILD  -> "En el Antiguo Egipto, el pan y la cerveza eran los alimentos mas importantes. Todos los dias, hombres y mujeres molian trigo para hacer harina. Con esa harina hacian mas de 40 tipos de pan de diferentes formas: redondos, triangulares o en forma de animales. La cerveza era la bebida favorita de ninos y adultos porque el agua del Nilo no siempre era limpia. Tambien comian pescado, cebollas, ajos, lentejas, higos y datiles. El modelo de panaderia que ves en la imagen viene de la tumba de un funcionario llamado Meketre, quien queria tener pan y cerveza para siempre en la otra vida."
            AgeGroup.TEEN   -> "La dieta egipcia giraba en torno al pan y la cerveza, los dos pilares de la alimentacion para todas las clases sociales. El pan se elaboraba con trigo emmer molido en piedras de cuarzo, lo que dejo huellas de desgaste en los dientes de las momias estudiadas. Se conocen mas de 40 variedades de pan. La cerveza, elaborada por fermentacion de pan de cebada, tenia un alto valor nutritivo y se usaba incluso como moneda de pago para los obreros que construyeron las piramides. El modelo de panaderia de la tumba de Meketre (hacia 2000 a.C.) que ilustra este articulo es uno de los testimonios mas completos de la gastronomia egipcia: muestra figurillas de cocineras amasando, horneando y preparando cerveza."
            AgeGroup.ADULT  -> "La alimentacion del Antiguo Egipto refleja una sociedad agricola altamente organizada. El pan y la cerveza constituian la base de la dieta de todas las clases sociales; el papiro Anastasi IV registra raciones diarias de dos jarras de cerveza y tres panes para trabajadores del Estado. El trigo emmer (Triticum dicoccum) y la cebada eran los cultivos principales, aprovechando las crecidas anuales del Nilo que depositaban limo fertil en los campos. El modelo de panaderia de la tumba de Meketre (Metropolitan Museum, 20.3.11), fechado hacia 2009-1998 a.C., ofrece una reconstruccion tridimensional del proceso productivo: figuras articuladas amasan, hornean y filtran cerveza en recipientes de ceramica. Los analisis bioquimicos de residuos en vasijas hallan restos de levadura, demostrando tecnicas de fermentacion controlada. La dieta se complementaba con legumbres, cebolla, ajo, pescado seco, aves de corral y, para las elites, carne de bovino. El auge de la apicultura en el Reino Nuevo permitio el uso generalizado de la miel como edulcorante en panes rituales."
        }

        // Art.2 — Vestimenta (imagen: Lady Tiye)
        1 -> when(age) {
            AgeGroup.CHILD  -> "Los egipcios usaban ropa hecha de lino, una planta que crecia junto al Nilo. El lino era blanco, fresco y comodo para el calor del desierto. Los ninos pequenos muchas veces jugaban sin ropa. Las mujeres llevaban vestidos largos y los hombres faldas cortas llamadas shendyt. Para protegerse del sol, se pintaban los ojos con kohl negro. Las joyas eran muy importantes: usaban collares, pulseras y aros hechos de oro, plata y piedras coloridas. La estatuilla que ves muestra a una dama noble con una peluca elaborada y un vestido de lino fino, igual que usaban las personas importantes."
            AgeGroup.TEEN   -> "El lino era el tejido principal en Egipto gracias a su frescura en el clima desertico. Existian diferentes calidades: el lino grueso para obreros y el lino real, tan fino que era casi transparente, reservado para la nobleza. La vestimenta masculina tipica era el shendyt, una falda corta sujeta con cinturon. Las mujeres nobles lucian vestidos tubulares ajustados con tirantes. Las pelucas de pelo humano o fibras vegetales eran simbolo de estatus y se usaban sobre la cabeza rapada, mas higienica en el calor. El kohl, elaborado de galena o malaquita, protegia los ojos del sol y tenia propiedades antisepticas. La estatuilla de Lady Tiye muestra la elegancia de la moda del Imperio Nuevo: lino plisado de alta calidad y joyeria compuesta de lapislazuli, cornalina y oro."
            AgeGroup.ADULT  -> "El lino (Linum usitatissimum) era el textil exclusivo del Antiguo Egipto; la lana se consideraba ritualmente impura. Los tejedores egipcios dominaron tecnicas de torsion en S y torsion en Z, produciendo desde telas de 200 hilos por centimetro para el vestido real hasta tejidos bastos para uso cotidiano. La estatuilla de Lady Tiye (Metropolitan Museum, 26.7.1393), del periodo Ramesida (ca. 1295-1069 a.C.), ilustra la moda de la elite del Imperio Nuevo: vestido de lino plisado con mangas acampanadas, peluca tripartita de pelo humano trenzado con anillos dorados y un elaborado collar usekh con cuentas de fayenza azul, cornalina y oro. El usekh era un elemento jerarquico: su tamano y materiales indicaban rango. Los cosmeticos no eran puramente esteticos: el kohl (mezcla de galena, cerusita y grasa animal) posee propiedades bacteriostaticas comprobadas. El aceite de ricino y la mirra hidrataban la piel. Los perfumes solidos en conos de cera sobre la cabeza, visibles en pinturas de banquetes, liberaban aromas durante horas."
        }

        // Art.3 — Familia (imagen: Nikare con esposa e hija)
        2 -> when(age) {
            AgeGroup.CHILD  -> "En el Antiguo Egipto, la familia era lo mas importante. El papa trabajaba en el campo, en talleres o para el faraon. La mama cuidaba la casa, cocinaba y ensenaba a los hijos. Los ninos ayudaban en casa y aprendian el oficio de sus padres. Solo los ninos de familias ricas podian ir a la escuela para aprender a escribir. La estatua que ves muestra a un hombre llamado Nikare con su esposa y su hija. Sus brazos rodeandolas significa que los amaba y los protegia. En Egipto, las mujeres podian tener propiedades, ir a juicio y divorciarse, algo muy avanzado para aquella epoca."
            AgeGroup.TEEN   -> "La familia egipcia era la unidad fundamental de la sociedad. El matrimonio no tenia ceremonia religiosa formal: la pareja simplemente comenzaba a vivir junta. Las mujeres tenian derechos legales notables para la epoca: podian poseer tierra, heredar bienes, hacer contratos y divorciarse. El divorcio era relativamente comun y debia compensarse economicamente a la esposa. Los contratos matrimoniales en papiro establecian la division de bienes en caso de separacion. El grupo familiar esculpido de Nikare (ca. 2371-2298 a.C.) es un ejemplo perfecto del ideal de familia egipcia: el hombre con postura frontal de autoridad, la esposa abrazandolo en signo de union y la hija a sus pies. Esta iconografia se repite en miles de estatuas funerarias, pues representar a la familia aseguraba su reunion en el Mas Alla."
            AgeGroup.ADULT  -> "La estructura familiar egipcia combinaba normas patriarcales con derechos femeninos sorprendentemente amplios para la Antiguedad. Los documentos legales del periodo Ptolemaico y anterior muestran a mujeres actuando como partes independientes en contratos de prestamo, compraventa y divorcio. El contrato matrimonial (sX n sHn) establecia los bienes aportados y la compensacion en caso de repudio. La tasa de nupcialidad era alta y el matrimonio preferente con primos o con hermanastra (no hermana biologica) era comun entre la realeza como mecanismo de concentracion de poder. El grupo estatuario de Nikare con su esposa y su hija (Metropolitan Museum, 08.201.1), tallado en caliza pintada hacia 2381-2323 a.C., encarna el ideal iconografico de la familia como unidad cohesionada: la posicion de los brazos de la esposa envolviendolo indica proteccion mutua. El tamaño relativo de las figuras —el hombre mayor que la esposa y esta mayor que la hija— refleja jerarquia, no proporciones reales. La colocacion de estatuas familiares en la tumba garantizaba la perpetuacion del vinculo en la eternidad."
        }

        // Art.4 — Juegos (imagen: Hounds and Jackals)
        3 -> when(age) {
            AgeGroup.CHILD  -> "A los ninos egipcios les encantaba jugar! Tenian munecas de madera o arcilla con pelo de verdad, pelotas de cuero rellenas de semillas, trompos y juguetes de animales con mandibulas que se movian. El juego de mesa mas famoso se llamaba Senet y parecia a las damas. Tambien habia un juego llamado Perros y Chacales que ves en la imagen: es un tablero con agujeros y fichas en forma de cabezas de perro y de chacal. Los adultos jugaban al Senet como si fuera un viaje al Mas Alla. El deporte favorito era la lucha libre, y tambien hacian carreras, lanzamiento de jabalina y natacion en el Nilo."
            AgeGroup.TEEN   -> "El ocio egipcio era rico y variado. El Senet, el juego de mesa mas antiguo conocido (ca. 3100 a.C.), era tan popular que los faraones lo llevaban a sus tumbas para jugar en la otra vida. El tablero Hounds and Jackals (Perros y Chacales), cuyo ejemplar del Museo Metropolitano data de ca. 1814-1805 a.C., es un juego de carreras con 58 agujeros numerados en un tablero de hipopotamo de marfil. Las fichas son miniaturas de cabezas de perro y chacal. Los deportes incluian lucha, natacion, remo, lanzamiento de jabalina, tiro con arco y un juego de pelota practicado desde posiciones elevadas. La musica acompanaba celebraciones: arpa, laul, flauta, oboe doble y sistro (cascabel) formaban parte del repertorio. Los banquetes de la elite incluian actuaciones de acrobatas y danzarinas."
            AgeGroup.ADULT  -> "El estudio del ocio en el Antiguo Egipto revela una sociedad que valorizaba el equilibrio entre trabajo y recreacion. El Senet, documentado desde el periodo Predinastico, evoluciono de juego de azar a metafora del viaje del alma a traves del Duat. El Libro de los Muertos muestra al difunto jugando al Senet como prueba de su idoneidad para el Mas Alla. El juego Hounds and Jackals (Metropolitan Museum, 26.7.1287a-t), elaborado hacia 1814-1805 a.C. en marfil, madera de ebano y cobre, es uno de los 23 ejemplares conocidos mundialmente. Sus fichas de cabeza zoomorfa corresponden a Anubis (chacal) y a una deidad canina; los agujeros numerados en el tablero con forma de hipopotamo hacen referencia a la cosmologia del Nilo. Los analisis iconograficos de las tumbas de Tel el-Amarna y Beni Hasan documentan actividades atleticas: lucha codificada, salto, natacion y juegos de pelota que prefiguran deportes modernos. La musica era inseparable del ritual: el conjunto arqueologico de la tumba de Rekhmire preserva representaciones de orquestas con instrumentos de cuerda, viento y percusion."
        }

        // Art.5 — Medicina (imagen: Estela magica de Horus)
        4 -> when(age) {
            AgeGroup.CHILD  -> "Los medicos egipcios eran muy listos! Sabian curar heridas, fijar huesos rotos y hasta hacer operaciones sencillas. Usaban plantas como el ajo y la cebolla para combatir enfermedades. Tambien hacian pociones con miel, porque la miel mata los germenes. Pero ademas de la medicina, usaban magia: recitaban oraciones y usaban amuletos para ahuyentar a los espiritus malvados que creian causaban las enfermedades. La estela que ves muestra al dios Horus nino de pie sobre cocodrilos. La gente la colocaba cerca del agua y la mojaba: el agua que la tocaba se volvia magica y curaba mordeduras de animales y enfermedades."
            AgeGroup.TEEN   -> "La medicina egipcia combinaba conocimiento empirico y ritual magico-religioso. El Papiro Edwin Smith (ca. 1600 a.C.) es el primer texto medico-quirurgico conocido: describe 48 casos de traumatismo con diagnostico, tratamiento y pronostico, incluyendo la primera descripcion del cerebro y el pulso. El Papiro Ebers cataloga mas de 700 remedios a base de plantas, minerales y productos animales. La miel, el aceite de ricino y el ajo tenian propiedades antibacterianas comprobadas. La estela magica de Horus sobre cocodrilos (Metropolitan Museum, 1989.281) era un objeto terapeutico: el agua vertida sobre ella se cargaba de poder divino y se bebia como antidoto contra venenos de animales. Este enfoque dual —cientifico y magico— no era contradictorio para los egipcios: el medico (swnw) y el sacerdote-mago (xry-Hb) colaboraban."
            AgeGroup.ADULT  -> "La medicina egipcia representa el primer sistema medico documentado de la historia. El Papiro Edwin Smith (Biblioteca de la Academia de Medicina de Nueva York, ca. 1600 a.C. pero basado en originales del Imperio Antiguo) introduce el metodo de observacion, palpacion, diagnostico diferencial y pronostico en 48 casos de trauma. Contrasta con el Papiro Ebers, que combina 700 prescripciones empiricas con formulas magicas. Los analisis de momias evidencian arteriosclerosis, tuberculosis, malaria y parasitosis intestinal, asi como intervenciones quirurgicas exitosas —amputaciones, reduccion de fracturas, drenaje de abscesos— con vendajes de lino impregnados de miel y resina. La estela magica de Horus cippus (Metropolitan Museum, 1989.281), del periodo Nectanebo I (360-343 a.C.), sintetiza la terapeutica egipcia: el contacto del agua con los relieves de Horus conquistando serpientes, escorpiones y cocodrilos transferia poder apotropaico al liquido, consumido como antidoto. El estudio bioquimico de residuos en vasos canopicos confirma el uso de aceites esenciales de cedro, mirra e incienso con propiedades antisepticas reales."
        }
        else -> "Contenido no disponible."
    }

    // ===================== ARQUITECTURA =====================
    "arquitectura" -> when(idx) {

        // Art.1 — Piramides (imagen: Mastaba de Perneb)
        0 -> when(age) {
            AgeGroup.CHILD  -> "Las piramides son las construcciones mas famosas del mundo! Fueron construidas hace mas de 4,500 anos como tumbas para los faraones. La mas grande es la Gran Piramide de Keops en Giza: mide casi 140 metros de alto y tiene mas de 2 millones de bloques de piedra. Pero antes de las piramides existian las mastabas, que son tumbas con forma de rectangulo achatado. La mastaba de Perneb que ves en la imagen fue construida en Saqqara hace unos 4,400 anos para un funcionario importante del faraon. Por dentro tiene capillas decoradas con relieves de Perneb recibiendo ofrendas de comida."
            AgeGroup.TEEN   -> "Las piramides evolucionaron a partir de las mastabas, tumbas rectangulares de adobe o piedra caliza. El arquitecto Imhotep disenno la primera piramide escalonada para el faraon Djoser en Saqqara (ca. 2667 a.C.), apilando seis mastabas decrecientes. La piramide perfecta de cuatro caras lisas se logro bajo el faraon Sneferu, quien construyo tres piramides experimentales en Meidum y Dashur. La Gran Piramide de Keops (Jufu) en Giza, con 138.8 m de altura actual, permanecio como el edificio mas alto del mundo durante 3,800 anos. La mastaba de Perneb (ca. 2381-2323 a.C.) exhibida en el Metropolitan Museum representa la forma arquitectonica que precedio a las piramides: una superestructura de piedra caliza sobre un pozo funerario subterraneo, con capillas de ofrendas decoradas en relieve."
            AgeGroup.ADULT  -> "La arquitectura funeraria egipcia sigue una linea evolutiva documentada arqueologicamente: desde la tumba en pozo predinastica hasta la mastaba de adobe del periodo Tinita, la mastaba de caliza del Imperio Antiguo, la piramide escalonada de Djoser y la piramide perfecta a partir de Sneferu. La mastaba de Perneb (Metropolitan Museum, 13.183.3), desmontada en Saqqara en 1913 y reconstruida en el museo, data de la Dinastia V (ca. 2381-2323 a.C.): su fachada de caliza blanca reproduce la fachada de palacio con nichos en serdab (camara de la estatua). Los relieves interiores documentan el sistema de provisiones para el ka del difunto: escenas de caza, pesca, elaboracion de pan, cerveza y tejido, garantizando el sustento eterno. El complejo piramidal de Giza —con sus tres piramides principales, la Esfinge, templos del Valle y calzadas procesionales— es el resultado de una organizacion estatal capaz de movilizar entre 20,000 y 30,000 trabajadores estacionales, segun los registros administrativos hallados en el puerto de Wadi al-Jarf."
        }

        // Art.2 — Templos (imagen: Templo de Dendur)
        1 -> when(age) {
            AgeGroup.CHILD  -> "Los templos egipcios eran la casa de los dioses! Solo los sacerdotes podian entrar a las partes mas internas. El templo que ves en la imagen se llama Templo de Dendur y fue construido hace mas de 2,000 anos cerca del rio Nilo, en Nubia. Tiene una puerta gigante llamada pilono, un patio abierto y una sala oscura donde vivian las estatuas de los dioses. En las paredes hay dibujos de faraones haciendo ofrendas a los dioses Isis y Osiris. El gobierno de Egipto lo regalo a los Estados Unidos en 1965 para salvarlo de una inundacion causada por la represa de Asuan. Hoy puedes verlo completo dentro del Museo Metropolitano de Nueva York."
            AgeGroup.TEEN   -> "El templo egipcio no era un lugar de culto publico como las iglesias modernas: era la residencia sagrada de la deidad. Solo el faraon y los sacerdotes podian acceder al naos, la camara mas interior donde habitaba la estatua del dios. La arquitectura tipica incluye: pilono (puerta monumental), patio hipetro (abierto al cielo), sala hipostila (columnas gigantes) y santuario. El Templo de Dendur (ca. 15 a.C.), erigido por el emperador romano Augusto para honrar a Isis y a dos principes nubios divinizados, es el unico templo egipcio completo fuera de Africa. El gobierno egipcio lo dono a EE.UU. en 1963 como agradecimiento por la ayuda durante el salvamento de Abu Simbel. Sus muros muestran a Augusto vestido como faraon, estrategia politica de legitimacion del poder romano."
            AgeGroup.ADULT  -> "El templo egipcio es la materializacion arquitectonica del mito de la creacion: el naos representa el montaculo primordial (benben), la sala hipostila el pantano primigenio y las columnas papiriformes y lotiformes la vegetacion que surgio del caos. El Templo de Dendur (Metropolitan Museum, 68.154), construido entre 15 a.C. y 10 a.C. por orden de Augusto, ilustra la continuidad iconografica bajo el dominio romano: las escenas de ofrenda muestran al emperador con doble corona, cartucho y nomenclatura faraonica, estrategia de legitimacion tipica del periodo ptolemaico-romano. El templo, originalmente en la orilla occidental del Nilo en Nubia, fue desmontado entre 1963 y 1968 en el marco del proyecto de salvamento de Nubia organizado por la UNESCO ante la construccion de la Presa de Asuan. Su translado al Metropolitan Museum en 1974 y su reconstruccion en el Ala Sackler (inaugurada 1978) representan uno de los proyectos de conservacion mas complejos del siglo XX."
        }

        // Art.3 — Esfinge (imagen: Esfinge de Hatshepsut)
        2 -> when(age) {
            AgeGroup.CHILD  -> "La Esfinge es una escultura con cuerpo de leon y cabeza de persona. El leon representaba fuerza y poder. La Gran Esfinge de Giza fue tallada directamente en la roca hace unos 4,500 anos y mide 73 metros de largo, lo que es mas que la mitad de un campo de futbol! La esfinge que ves en la imagen es de la faraona Hatshepsut, una mujer que goberno Egipto como si fuera un rey. Ella se hizo representar como esfinge para mostrar que tenia el mismo poder que cualquier faraon. Hatshepsut fue una de las gobernadoras mas importantes de Egipto: construyo muchos templos, envio expediciones comerciales y trajo tesoros de tierras lejanas."
            AgeGroup.TEEN   -> "Las esfinges egipcias —con cuerpo de leon y cabeza real o divina— simbolizaban la fusion del poder del faraon con la ferocidad del leon, guardian del horizonte solar. La Gran Esfinge de Giza (ca. 2558-2532 a.C.) fue tallada en un afloramiento de caliza en el complejo funerario de Khafre y mide 73 m de largo por 20 m de alto. La esfinge de granito de Hatshepsut (Metropolitan Museum, 31.3.166) es uno de los mas de 200 ejemplares que la faraona encargo para el templo de Deir el-Bahari. Hatshepsut (ca. 1479-1458 a.C.) fue la segunda mujer en asumir el titulo de faraon; adopto la iconografia masculina —barba postiza, nemes y corona doble— para reforzar su legitimidad. Tras su muerte, Tutmosis III ordeno borrar su nombre e imagen de los monumentos, pero siglos despues los arqueologos lograron reconstruir su historia."
            AgeGroup.ADULT  -> "La esfinge es un hibrido iconografico con un largo recorrido semantico: el cuerpo leonino aporta la cualidad solarapotropaica (shesep-ankh, imagen viviente) mientras el rostro real identifica al gobernante con Ra-Horakhty. La Gran Esfinge de Giza, tallada en la caliza del Muqqatam in situ, presenta en la Estela del Sueno de Tutmosis IV (18a Dinastia) el primer texto que la nombra como Hor-em-akhet, consagrando su culto solar independiente. La esfinge granitocida de Hatshepsut (Metropolitan Museum, 31.3.166), del reinado de Hatshepsut (ca. 1479-1458 a.C.), pertenece a una serie producida para el corredor procesional del templo de Deir el-Bahari en Luxor. Su cara combina rasgos femeninos —pomulos redondeados, nariz fina— con el nemes y la barba trenzada ritual. El programa damnatio memoriae emprendido por Tutmosis III implico la interment de estas esfinges bajo el piso del templo, lo que paradojicamente las conservo; fueron descubiertas en excavaciones del Metropolitan Museum (1926-1928)."
        }

        // Art.4 — Valle de los Reyes (imagen: Sarcofago de Harkhebit)
        3 -> when(age) {
            AgeGroup.CHILD  -> "El Valle de los Reyes es un lugar secreto en Egipto donde los faraones escondian sus tumbas bajo la tierra. Despues de las piramides, los faraones decidieron que era mejor hacer tumbas subterraneas para que los ladrones no encontraran sus tesoros. Las tumbas tienen largos pasillos, trampas y camaras llenas de muebles, joyas y comida para la otra vida. El sarcofago que ves en la imagen es el ataud de piedra de un funcionario importante. Tiene inscripciones magicas del Libro de los Muertos que lo ayudarian a llegar al paraiso egipcio. En 1922, el arqueolo Howard Carter descubrio la tumba casi intacta del faraon Tutankamon, llena de miles de objetos de oro."
            AgeGroup.TEEN   -> "El Valle de los Reyes (Wadi Biban el-Muluk) fue el cementerio real del Imperio Nuevo (ca. 1550-1070 a.C.), elegido por su aislamiento y por la montana natural con forma piramidal que lo domina. Se conocen 63 tumbas numeradas (KV1-KV63 y algunas mas recientes). Las tumbas tienen planta en L o en linea recta, con corredores descendentes, antecamaras y camara sepulcral. El sarcofago monolitico de Harkhebit (Metropolitan Museum, 11.150.7), del periodo Tardio (Dinastia 26, ca. 664-525 a.C.), es un ejemplar excepcional: su cubierta pesa varias toneladas y esta cubierto de inscripciones del Libro de los Muertos en hieratico y jeroglificos. El descubrimiento de KV62 (Tutankamon) por Howard Carter en 1922 es el hallazgo arqueologico mas meditico del siglo XX: la camara del tesoro contenia mas de 5,000 objetos, entre ellos la mascara de oro macizo."
            AgeGroup.ADULT  -> "La eleccion del Valle de los Reyes como necropolis real desde Tutmosis I (ca. 1504 a.C.) responde a una estrategia defensiva y teologica: la montana pyramidal natural (al-Qurn) consagraba el lugar a Meretseger, diosa cobra protectora, y el aislamiento dificultaba el acceso. El sarcofago de Harkhebit (Metropolitan Museum, 11.150.7), Saita (Dinastia 26), es un ejemplo de la tradicion del sarcofago compuesto —caja exterior de basalto, interior de madera— con textos del Libro de los Muertos, Textos de las Piramides adaptados y representaciones de dioses funerarios en bajorrelieve. El renacimiento arcaizante de la Dinastia 26 se manifiesta en la copia directa de formulas del Imperio Antiguo. La topografia geomorfica del valle, estudiada con LiDAR y tomografia de resistividad electrica, sugiere la existencia de camaras no excavadas, avalando la hipotesis de nuevas tumbas por descubrir segun el proyecto Scan Pyramids y estudios recientes del EES."
        }

        // Art.5 — Obeliscos (imagen: Hatshepsut arrodillada)
        4 -> when(age) {
            AgeGroup.CHILD  -> "Los obeliscos son como lapices de piedra gigantes que los egipcios construyeron para honrar al dios Sol. Estan cubiertos de jeroglificos que cuentan las hazanas del faraon. La punta, llamada piramidion, estaba cubierta de oro o de una mezcla de oro y plata llamada electrum para que brillara con el sol. La faraona Hatshepsut mando construir los obeliscos mas altos de su epoca en el templo de Karnak: median casi 30 metros de alto! La estatua que ves muestra a Hatshepsut arrodillada ofreciendo vasijas a los dioses. Era una costumbre que los faraones se mostraran haciendo ofrendas para demostrar su devocion."
            AgeGroup.TEEN   -> "Los obeliscos (tekhen en egipcio antiguo) eran monolitos de granito rosa de Asuan, considerados manifestaciones del benben, la piedra sagrada primordial. Su piramidion de electrum (aleacion natural de oro y plata) captaba el primer rayo de sol del amanecer, simbolizando la creacion. Los dos obeliscos de Hatshepsut en Karnak, erigidos en su ano 16 de reinado (ca. 1458 a.C.), median originalmente 28 y 29.5 metros y pesaban 323 y 343 toneladas respectivamente. La estatua de Hatshepsut arrodillada (Metropolitan Museum, 29.3.2), del templo de Deir el-Bahari, es una de las pocas estatuas femeninas en posicion de ofrenda. Los obeliscos egipcios fueron tan admirados que emperadores romanos trasladaron 13 a Roma; hoy hay mas obeliscos egipcios en Roma que en Egipto. El obelisco de la Plaza del Popolo, por ejemplo, procede del templo de Ramses II en Heliupolis."
            AgeGroup.ADULT  -> "El obelisco es la quintaesencia de la teologia solar egipcia: el monolito reproduce la piedra benben del templo de Ra en Heliopolis, la cual segun el mito de la creacion emergio del caos primordial (Nun) y recibio el primer rayo solar. El piramidion de electrum —documentado en el papiro de Amenhotep III donde se registran los costos de doramiento— actuaba como heliostato, proyectando reflejos luminosos sobre el patio del templo durante el amanecer. Los obeliscos de Hatshepsut en Karnak, erigidos en su ano 16 segun la inscripcion en la base, son los mas altos que permanecen en Egipto (29.56 m el superviviente). La logistica de su transporte desde las canteras de Asuan ha sido estudiada mediante modelos hidraulicos que demuestran el uso de barcazas especiales de 60 m de eslora. La estatua de Hatshepsut en acto de presentacion de vasijas nu (Metropolitan Museum, 29.3.2) pertenece al programa iconografico del templo de Deir el-Bahari: la posicion de rodillas —inusual en estatuas reales masculinas— subraya la piedad filial de la faraona hacia Amun."
        }
        else -> "Contenido no disponible."
    }

    // ===================== ARTE =====================
    "arte" -> when(idx) {

        // Art.1 — Jeroglificos (imagen: Santuario con jeroglificos)
        0 -> when(age) {
            AgeGroup.CHILD  -> "Los jeroglificos son los dibujos que usaban los egipcios para escribir. Hay mas de 700 simbolos diferentes: algunos representan letras, otros palabras enteras. Dibujaban pajaros, serpientes, ojos, personas y muchas cosas mas. Solo los escribas —personas que estudiaban muchos anos— sabian leer y escribir jeroglificos. Los demas no sabian. Durante mas de 1,400 anos nadie entendio los jeroglificos hasta que en 1822 un frances llamado Jean-Francois Champollion descifro su secreto usando la Piedra Rosetta, que tiene el mismo texto en tres idiomas. El santuario que ves esta lleno de jeroglificos tallados en piedra que cuentan el nombre y los logros del faraon Amenemhat."
            AgeGroup.TEEN   -> "El sistema de escritura jeroglifica es uno de los mas complejos de la historia: combina logogramas (simbolos que representan palabras), fonogramas (simbolos que representan sonidos) y determinativos (simbolos que clasifican el significado sin pronunciarse). Se usaba para textos religiosos y monumentales, mientras que el hieratico y luego el demotico se usaban para textos administrativos cotidianos. El santuario de caliza con jeroglificos de Amenemhat (Metropolitan Museum, 12.182.3), del Reino Medio (ca. 1878-1840 a.C.), muestra como los textos sagrados organizaban el espacio arquitectonico: cada pared narra las ofrendas, titulos y genealogia del dedicante. El descifrado de Jean-Francois Champollion en 1822 se baso en la Piedra Rosetta (196 a.C.), que contiene un decreto real en jeroglificos, demotico y griego, permitiendo la comparacion sistematica."
            AgeGroup.ADULT  -> "La escritura jeroglifica (Mdw nTr, 'palabras de los dioses') es un sistema logofonografico con aproximadamente 750 grafemas en el Imperio Antiguo, ampliados a mas de 6,000 en el periodo ptolemaico. Su estructura tripartita —logogramas, fonogramas uniliteros/biliteros/triliteros y determinativos— confiere una redundancia semantica que ha facilitado el descifrado moderno. El santuario de Amenemhat III (Metropolitan Museum, 12.182.3), tallado en caliza hacia 1840-1800 a.C., exemplifica la funcion apotropaica de los jeroglificos: el cartucho real del faraon (nombre en oval cerrado) y las formulas de ofrendas (jrp formula) inscritos en las jambas garantizaban la proteccion divina del espacio y la identidad juridica del donante. El descifrado de Champollion (1822), publicado en la Lettre a M. Dacier, parte del analisis de la Piedra Rosetta (BM EA 24) y de los obeliscos de Philae para establecer la correspondencia fonologica del cartucho de Ptolomeo con su forma griega. La epigrafía computacional moderna aplica OCR entrenado con corpus jeroglificos para catalogar sistematicamente los 5 millones de inscripciones estimadas."
        }

        // Art.2 — Pintura mural (imagen: Gato matando serpiente)
        1 -> when(age) {
            AgeGroup.CHILD  -> "Los egipcios eran pintores increibles! Decoraban las paredes de las tumbas con colores muy brillantes que han durado miles de anos. Usaban seis colores principales: rojo, amarillo, verde, azul, blanco y negro, todos hechos de minerales molidos mezclados con huevo o goma arabiga. Una de las pinturas mas famosas de las tumbas muestra a un gato grande —que representa al dios Ra— cortandole la cabeza a una serpiente maligna llamada Apofis. Esta imagen que ves viene de la tumba de Sennedjem, un artista que decoraba las tumbas de otros. En Egipto, los gatos eran animales sagrados protegidos por ley. Matar uno era un delito muy grave."
            AgeGroup.TEEN   -> "La pintura mural egipcia siguio convenciones rigidas durante mas de 3,000 anos: la figura humana se representa con cabeza y piernas de perfil pero ojo y torso de frente, maximizando la legibilidad iconografica. La paleta clasica incluia seis pigmentos minerales —ocre rojo (hematita), ocre amarillo (limonita), verde egipcio (malaquita o cuprorivaita), azul egipcio (CaCuSi2O6, el primer pigmento sintetico de la historia), blanco (caliza) y negro (carbon)—. La escena del gato bajo el persea decapitando a la serpiente Apofis (Metropolitan Museum, tumba de Sennedjem, TT1, ca. 1295-1213 a.C.) ilustra el capitulo 17 del Libro de los Muertos: Ra en forma felina destruye cada noche a Apofis, garantizando el amanecer. Sennedjem fue un artesano real (Servidor en el Lugar de la Verdad) que vivia en Deir el-Medina, el pueblo de los constructores de tumbas."
            AgeGroup.ADULT  -> "La pintura mural egipcia opera bajo un codigo de representacion aspektiv (perspectiva cognitiva, segun Heinrich Schafer): cada elemento se dibuja desde su angulo mas reconocible, resultando en la figura humana compuesta con cabeza de perfil, ojo frontal, hombros frontales y piernas de perfil. Este sistema no es ingenuidad tecnica sino una eleccion semiotica: garantizar la identificabilidad de cada parte del cuerpo asegura la integridad magica de la imagen. La paleta sexcromatica utilizo el azul egipcio (CaCuSi2O6), el primer pigmento sintetico de la historia, producido calcinando cuarzo, malaquita y calcita a 900 C. La escena del gato cortando la cabeza de Apofis bajo el arbol persea, procedente de la tumba de Sennedjem (TT1, Deir el-Medina, ca. 1295-1213 a.C.) y reproducida en el Metropolitan Museum (30.4.2), se relaciona con el capitulo 17 del Libro de los Muertos y la iconografia del Libro de las Cavernas, donde Ra-Atum adopta forma felina para combatir al caos serpentiforme. El analisis por espectroscopia Raman de pigmentos similares confirma la presencia de goethita, hematita y cuprorivaita con aglutinante de polisacaridos."
        }

        // Art.3 — Escultura (imagen: Hatshepsut escultura)
        2 -> when(age) {
            AgeGroup.CHILD  -> "Los escultores egipcios eran artistas muy habilidosos que tallaban estatuas de piedra, madera y bronce. Las estatuas servian para que el espiritu del muerto pudiera habitarlas y recibir las ofrendas. La escultura que ves muestra a la faraona Hatshepsut sentada. Tiene una peluca y una corona. Su cara es serena y perfecta, como la de una diosa. Los escultores empezaban dibujando una cuadricula en la piedra para asegurarse de que las proporciones fueran correctas. Las estatuas mas grandes, los colosos, podian medir 20 metros de alto! Los colosos de Memnon, frente al Valle de los Reyes, eran tan grandes que cuando el viento los golpeaba producian un sonido misterioso."
            AgeGroup.TEEN   -> "La escultura egipcia se rige por el canon de proporciones: el cuerpo humano se divide en 18 cuadros (o 21 en el periodo tardio) desde la planta del pie hasta la linea del cabello, garantizando la consistencia de las figuras independientemente del tamano. Los materiales mas valorados eran la caliza blanca, el granito rosa de Asuan, el esquisto verde, el basalto negro y la cuarcita. La escultura de Hatshepsut sentada (Metropolitan Museum, 29.3.3), tallada en granito hacia 1479-1458 a.C. para el templo de Deir el-Bahari, muestra la convencion de la representacion real: postura frontal rigida, manos sobre las rodillas, mirada al frente. La iconografia combina atributos masculinos (nemes, barba ritual) con rasgos faciales femeninos. Tras la damnatio memoriae de Tutmosis III, esta estatua fue fragmentada y enterrada en una fosa, descubierta por el Metropolitan Museum en las excavaciones de 1926-1928."
            AgeGroup.ADULT  -> "La escultura egipcia articula una relacion dialectica entre la tridimensionalidad formal y la bidimensionalidad ritual: la estatua de culto (xntj-S) es ante todo un soporte para el ka del difunto, no una obra de arte autonoma en sentido moderno. El canon de proporciones —18 cuadros en el Imperio Antiguo y Medio, 21 en el periodo Tardio— garantiza la integridad magica de la figura independientemente de su escala, desde los amuletos de 2 cm hasta los colosos de Abu Simbel de 20 m. La estatua sedente de Hatshepsut en granito (Metropolitan Museum, 29.3.3), tallada en los talleres reales de Karnak hacia 1479-1458 a.C., pertenece al programa escultorio del templo de Deir el-Bahari, donde las estatuas flanqueaban los corredores procesionales. El analisis petrograficamente la identifica con granito de Asuan (Formacion Rosa de Asuan). La fractura intencional en el cuello y la eliminacion de los cartuchos —intervenciones atribuibles al reinado de Tutmosis III— y el enterramiento posterior permitieron la conservacion excepcional del pigmento rojo original en la piel de la faraona, identificado por fluorescencia de rayos X como hematita (Fe2O3)."
        }

        // Art.4 — Mascara (imagen: Mascara Hatnefer)
        3 -> when(age) {
            AgeGroup.CHILD  -> "Las mascaras funerarias cubrian el rostro de los muertos para que los dioses los reconocieran en la otra vida. La mas famosa es la mascara de oro de Tutankamon que pesa 11 kilos de oro puro! La mascara que ves en la imagen es de una mujer llamada Hatnefer, la mama de un funcionario importante. Esta hecha de cartonaje —capas de lino pegadas con yeso— y luego pintada de dorado. Los ojos estan hechos de obsidiana negra y alabastro blanco, que se ven muy reales. Las mascaras tenian inscripciones del Libro de los Muertos que protegian al difunto y le daban el poder de ver, respirar y hablar en el otro mundo."
            AgeGroup.TEEN   -> "La mascara funeraria egipcia tenia una funcion magico-religiosa precisa: siendo el ka (espiritu vital) incapaz de reconocer el cuerpo si este quedaba desfigurado, la mascara garantizaba una identidad permanente e indestructible. La mascara de Hatnefer (Metropolitan Museum, 36.3.1), madre del arquitecto Senenmut (confidente de Hatshepsut), data de ca. 1492-1473 a.C. Esta construida en cartonaje —capas de lino o papiro impregnadas de yeso y pintadas— con incrustaciones de obsidiana, alabastro y pasta de vidrio de color. La mascara de Tutankamon (Museo Egipcio, JE 60672), el ejemplo mas conocido, pesa 10.23 kg de oro con incrustaciones de lapislazuli, cornalina, cuarzo, obsidiana y turquesa. Sus inscripciones en el cuello y hombros corresponden al capitulo 151b del Libro de los Muertos: un sortilegio para proteger los miembros del difunto."
            AgeGroup.ADULT  -> "La mascara funeraria egipcia es el punto de convergencia entre la tecnologia artesanal, la teologia del ka y la estetica de la eternidad. El cartonaje —tecnica documentada desde el Imperio Medio— se obtiene superponiendo tiras de lino o papiro sobre una forma provisional, impregnandolas con yeso calcinado (CaSO4·½H2O) y poliendolas antes de la decoracion policroma. La mascara de Hatnefer (Metropolitan Museum, 36.3.1), fechada en la Dinastia XVIII temprana (ca. 1492-1473 a.C.), fue descubierta in situ en la tumba MMA 71 de Deir el-Bahari junto con el ajuar completo de la madre de Senenmut. Los ojos de obsidiana magnetica y alabastro translucido reproducen la convencion iconografica del ojo sagrado (wedjat). La inscripcion en la base del cuello recita el capitulo 151b del Libro de los Muertos (formula para proteger la cabeza del difunto), estableciendo la continuidad identitaria del ka. Los estudios de fluorescencia de rayos X en mascaras similares identifican oro de alta pureza (>95%) en las areas faciales y plata en los surcos de la peluca, reflejando la cosmologia estelar (oro=sol, plata=luna)."
        }

        // Art.5 — Arte funerario (imagen: Sarcofago Henettawy)
        4 -> when(age) {
            AgeGroup.CHILD  -> "Los sarcofagos son los atades decorados donde los egipcios guardaban a sus muertos. A veces habia hasta tres o cuatro caxas una dentro de la otra, como una muneca rusa. Por fuera estaban llenos de pinturas y jeroglificos con oraciones para proteger al muerto. El sarcofago que ves es de Henettawy, una cantora que cantaba para el dios Amun-Ra. Tiene pinturas de dioses, ojos magicos llamados wedjat, y una cara muy bonita con peluca negra. Dentro del sarcofago, junto a la momia, ponian figuras pequenitas llamadas ushebtis que actuarian como sirvientes en la otra vida. Tambien ponian vasos canopicos con los organos del muerto para que los tuviera en la eternidad."
            AgeGroup.TEEN   -> "El sarcofago egipcio es un sistema de proteccion progresiva: la momia en su envoltura de lino, dentro de una o varias cajas de madera decorada, dentro de un sarcofago de piedra en la camara funeraria. El sarcofago de Henettawy (Metropolitan Museum, 25.3.182), cantora de Amun-Ra del Tercer Periodo Intermedio (ca. 1000-945 a.C.), es un ejemplar del estilo tebano tardio: fondo amarillo simbolizando el oro de la eternidad, escenas del Libro de los Muertos en bandas horizontales, y el dios Nut con alas extendidas en el interior de la tapa para abrazar y proteger a la difunta. Los ojos wedjat pintados a la altura del pecho permitirian a la momia 'ver' hacia el este, donde sale el sol. Los ushebtis (figuras de fayenza azul depositadas en el ajuar) eran sustitutos magicos del difunto para realizar las corveas agricolas en el Mas Alla."
            AgeGroup.ADULT  -> "El sarcofago egipcio es el artefacto mas complejo de la cultura material funeraria: articula en un mismo objeto la funcion contenedora, la proteccion magica, la identificacion del difunto y la narracion escatologica. El sarcofago de la Chantress de Amun-Ra Henettawy (Metropolitan Museum, 25.3.182), datado en el Tercer Periodo Intermedio (ca. 1000-945 a.C.), pertenece al estilo tebano de fondo amarillo (que evoca el oro de la inmortalidad) con policromia en rojo, azul, verde y blanco. El programa iconografico integra: escenas del Libro de los Muertos (pesaje del corazon, juicio de Osiris, campo de Iaru), textos de los Textos de los Sarcofagos adaptados, representacion de los cuatro hijos de Horus en las jambas y la diosa Nut en el interior de la tapa con las alas desplegadas en gesto de proteccion. El analisis dendrocronologico de la madera identifica Ficus sycomorus (sicamoro), arbol funerario por excelencia. La estratigrafia de la policromia, estudiada con microscopio electronico de barrido, muestra hasta seis capas de yeso y pigmento, evidenciando intervenciones de restauracion antiguas durante el periodo ptolemaico."
        }
        else -> "Contenido no disponible."
    }

    else -> "Selecciona una seccion para ver su contenido."
}
