package com.example.aplicacionegipto.ui.theme

import androidx.compose.ui.graphics.Color

val GoldPharaoh       = Color(0xFFD4A843)
val GoldLight         = Color(0xFFE8C76B)
val GoldDark          = Color(0xFFB8892E)
val SandPapyrus       = Color(0xFFF5E6C8)
val SandLight         = Color(0xFFFAF0DC)
val SandDark          = Color(0xFFDCC89E)
val LapisLazuli       = Color(0xFF1B3A5C)
val LapisLight        = Color(0xFF2A5580)
val TurquoiseEgypt    = Color(0xFF2E8B8B)
val TurquoiseLight    = Color(0xFF45A5A5)
val OcreEgypt         = Color(0xFFC17817)
val RedDesert         = Color(0xFFA0522D)
val TerraCotta        = Color(0xFFCC6B49)
val KohlBlack         = Color(0xFF1A1A1A)
val NileGreen         = Color(0xFF3D6B4F)
val NightSky          = Color(0xFF0D1B2A)
val SurfaceLight      = Color(0xFFFDF8EF)
val SurfaceDark       = Color(0xFF1C1410)
val CardLight         = Color(0xFFFFF9F0)
val CardDark          = Color(0xFF2A2018)
val TextOnLight       = Color(0xFF2C1810)
val TextOnDark        = Color(0xFFF5E6C8)
val TextMuted         = Color(0xFF8B7355)
val HighContrastBg    = Color(0xFF000000)
val HighContrastText  = Color(0xFFFFFFFF)
val HighContrastAccent = Color(0xFFFFD700)
